### PR TITLE
fix: update MakeTransferRequest tx type

### PR DESCRIPTION
**Pull request by beeman**

### CODE REVIEW

**Comment by RamirezAlex** [comment]
Is this ready to review?

**Comment by beeman** [comment]
> Is this ready to review?

For this, we are waiting on a reply from Sam at #231

**Comment by samdowd** [comment]
Sorry for the delay. Looks like this is still generating `MakeTransferRequest.tx` as `Any` for ios. So this does not fix the issue.

**Comment by beeman** [comment]
> Sorry for the delay. Looks like this is still generating `MakeTransferRequest.tx` as `Any` for ios. So this does not fix the issue.

I adjusted it to a `Uint8Array` as suggested on our call. Hope this helps. If not, probably good to try one of the other things we discussed.

**Comment by samdowd** [comment]
No dice. I'll try some other ideas.

**Comment by beeman** [comment]
> No dice. I'll try some other ideas.

Thanks for confirming Sam. I'll close this one, we can add other tweaks if needed.

**Pull request closed without merging**
