### PR TITLE
feat: add KineticAccount abstraction for using the SDK with even less boilerplate

### PR DESCRIPTION
**Pull request by beeman**
This takes some of the good things from the Agora mobile SDK, where they had the concept of 'the account' - basically a default keypair that you would use for most operations. 

If we decide to go with this, we should add this `KineticAccount` abstraction to the other SDKs too, and use this as the default way to use the SDK.

Using this abstraction, the flow is something like this:

```ts
const owner = Keypair.random() // or get it from some secure storage...
const kinetic = await KineticAccount.setup({
  endpoint: 'https://path.to.kinetic', // <- the options extend the options from KineticSdk.setup()
  environment: 'devnet',
  index: 1,
  owner, // <- in addition, we pass the owner into the setup
})

// Now, we can use all operations without passing in the `owner` or `account`:
const createTx = await kinetic.createAccount()

const airdropTx = await kinetic.requestAirdrop({ amount: "42" })

const balance = await kinetic.getBalance()

const transferTx = await kinetic.makeTransfer({ amount: "42", destination: "Bob..." })
```

In addition, we still have access to the underlying classes:

```
// the KineticSdk class
const otherBalance = await kinetic.sdk.getBalance({ account: 'otherAccount' });
// the Keypair class
const owner = kinetic.owner
```

What do you think @RamirezAlex @richardmands @samdowd?

### CODE REVIEW

**Comment by RamirezAlex** [comment]
Code looks good, as well as the proposal. It took me a bit to wrap my head around the example you gave because having multiple account setup(I don't see why...) was confusing with:

```js
const kinetic = await KineticAccount.setup({
  endpoint: 'https://path.to.kinetic', // <- the options extend the options from KineticSdk.setup()
  environment: 'devnet',
  index: 1,
  owner, // <- in addition, we pass the owner into the setup
})
```

However, I see that it is OK to have:

```js
...
const alice = await KineticAccount.setup({
  endpoint: 'https://path.to.kinetic', // <- the options extend the options from KineticSdk.setup()
  environment: 'devnet',
  index: 1,
  owner: aliceKeypair,
})

const bob = await KineticAccount.setup({
  endpoint: 'https://path.to.kinetic', // <- the options extend the options from KineticSdk.setup()
  environment: 'devnet',
  index: 1,
  owner: bobKeypair,
})
...
```

**Comment by samdowd** [comment]
I agree with this and was playing with something similar in the mobile SDKs before we standardized. It just makes sense in most use cases to have one wallet. And loading it up into the SDK not only makes things easier but safer. The less developers have to pass around a private key in their own code the better. Just one more way to take away the "scary" parts of crypto.

Just to confirm, line 2 in your first snippet should say `Kinetic.setup` nor `KineticAccount.setup` right? If so, I like the implementation. An optional owner parameter is very clean.

**Comment by beeman** [comment]
> Just to confirm, line 2 in your first snippet should say `Kinetic.setup` nor `KineticAccount.setup` right? If so, I like the implementation. An optional owner parameter is very clean.

No, the goal is to add a separate class `KineticAccount` that wraps around `KineticSdk` and `Keypair`, basically merge them - that way we won't lose any of the current use cases, and add a convenience layer on top of it.

**Comment by samdowd** [comment]
> No, the goal is to add a separate class KineticAccount that wraps around KineticSdk and Keypair, basically merge them - that way we won't lose any of the current use cases, and add a convenience layer on top of it.

Ah okay. In that case I'm not in love with the name. And I wonder if we could do it differently. Maybe I'm looking at this wrong, but why not handle it like mint? Make `owner` an optional parameter on the SDK setup function, then make the `owner` parameter optional on each function it's currently required on. And make a `getOwner` for those functions like `getMint` that uses the provided owner if one is passed in the parameter, uses the owner that was passed in the SDK setup if not, and throws if neither exists. That seems cleaner from where I'm sitting but maybe I'm missing something or this makes less sense in the other SDKs I haven't touched.

**Comment by beeman** [comment]
> > No, the goal is to add a separate class KineticAccount that wraps around KineticSdk and Keypair, basically merge them - that way we won't lose any of the current use cases, and add a convenience layer on top of it.
> 
> Ah okay. In that case I'm not in love with the name. And I wonder if we could do it differently. Maybe I'm looking at this wrong, but why not handle it like mint? Make `owner` an optional parameter on the SDK setup function, then make the `owner` parameter optional on each function it's currently required on. And make a `getOwner` for those functions like `getMint` that uses the provided owner if one is passed in the parameter, uses the owner that was passed in the SDK setup if not, and throws if neither exists. That seems cleaner from where I'm sitting but maybe I'm missing something or this makes less sense in the other SDKs I haven't touched.

This is very good feedback - I am going to close this issue and give it some more thought. 

I think we should look at this for the next major release of Kinetic, ideally when we will look at connecting the Solana wallet adapter.

**Pull request closed without merging**
